### ISSUE TITLE
updateChildren.js中代码有报错，oldCh[oldStartIdx]这个存在为undefined的情况

### ISSUE THREAD

**Issue by whl1022** [M-cheng-web/vue-sound-snabbdom#1]
在115行， 这块代码
parentElm.insertBefore(createElement(newCh[i]), oldCh[oldStartIdx].elm );
应修改为
parentElm.insertBefore(createElement(newCh[i]), oldCh[oldStartIdx] ? oldCh[oldStartIdx].elm : null );

**Comment by M-cheng-web** [comment]
好的谢谢，感谢提出issue




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "M-cheng-web/vue-sound-snabbdom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月26日(星期五) 上午10:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[M-cheng-web/vue-sound-snabbdom] updateChildren.js中代码有报错，oldCh[oldStartIdx]这个存在为undefined的情况 (Issue #1)





 
在115行， 这块代码
 parentElm.insertBefore(createElement(newCh[i]), oldCh[oldStartIdx].elm );
 应修改为
 parentElm.insertBefore(createElement(newCh[i]), oldCh[oldStartIdx] ? oldCh[oldStartIdx].elm : null );
